apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: ragulnd/testnodejs:tagversion
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

#service type load balancer
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-test
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

